name: Build test
on:
  push:
    branches-ignore:
    - 'master'
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: specify-tag
      id: bumptag
      run: echo "::set-output name=new_tag::$(git describe HEAD --tags)"
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        build_args: TAG=${{ steps.bumptag.outputs.new_tag }}
        username: ${{ secrets.ROBOT_NAME }}
        password: ${{ secrets.ROBOT_PASS }}
        registry: quay.io
        repository: thehyve/report-vulnerability
        tags: ${{ steps.bumptag.outputs.new_tag }}
