name: Build test
on:
  push:
    branches-ignore:
    - 'master'
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: specify-tag
      id: bumptag
      run: echo "::set-output name=new_tag::$(git describe HEAD --tags)"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        tags: quay.io/thehyve/report-vulnerability:${{ steps.bumptag.outputs.new_tag }}
