name: Build test
on:
  push:
    branches-ignore:
    - 'master'
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: specify-tag
      id: bumptag
      run: echo "new_tag=$(git describe HEAD --tags)" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: quay.io/thehyve/report-vulnerability:${{ steps.bumptag.outputs.new_tag }}
